version: "3"

networks:
  app-tier:
    driver: bridge


services:
  slave-pg:
    build:
      context: ../.
      dockerfile: diplom/DockerfileDb
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - "5433:5432"
    networks:
      - app-tier
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 10s
    # restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 4G
  copy_deamon:
    build:
      context: ../.
      dockerfile: diplom/DockerfileCopy
    env_file: copy_deamon.env
    networks:
      - app-tier
    # restart: unless-stopped
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1'
    #       memory: 4G
  save_deamon:
    build:
      context: ../.
      dockerfile: diplom/DockerfileSave
    env_file: save_deamon.env
    networks:
      - app-tier
  master-pg:
    build:
      context: ../.
      dockerfile: diplom/DockerfileDb
    ports:
      - "5434:5432"
    networks:
      - app-tier